title: Constraint Capers
email: digitalbricklayer@gmail.com
description: >
  This site is the digital home of Jack Hughes a journeyman programmer from Leeds, UK. He is a professional software developer specialising in the .NET stack. He currently works for OPENXTRA Ltd.. His current pet project is writing a constraint satisfaction workbench.
baseurl: ""
url: "https://digitalbricklayer.github.io"
twitter_username: mrjackhughes
github_username:  digitalbricklayer
copyright_notice: "Copyright &copy; 2015-2018 Jack Hughes. All rights reserved."
permalink: /:slug/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - run-dev-server.sh

google_analytics: UA-71383-42
